name: Deploy
# Restarts the service that maintains the website.
on:
    push:
        branches:
            - master

jobs:
    build:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Execute remote ssh commands
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                script: whoami