name: Publish Docker
# This workflow is triggered on pushes to master.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lsaether/martingale
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}