name: Publish to Docker and Serve
# This workflow is triggered on pushes to master.
on: 
  push:
    branches:
      - master

jobs:
  build_docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        with:
          name: lsaether/martingale
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: GITHUB_ACCESS_TOKEN,GIST_ID,CLIENT_SECRET
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: docker pull lsaether/martingale; systemctl restart martingale-website